# Use Node.js Alpine base image
FROM node:alpine

#Create and set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json /app/

#Install dependencies
RUN npm Install

# Copy the entire codebase to the working directory
COPY . /app/

# Expose the port your app runs on
EXPOSE 5173

# Define the command to start your application 
CMD ["npm", "run", "dev"]

```

4. **Build  the Docker Image:**

Build the Docker image using the following command:

```bash
docker build -t react-app .
 ```
 Replace your-react-app with a suitable image-name
 Run the Docker container:

Run the Docker container using the following command:
    ```bash
            docker run -p 3000:3000 -d software-estimation-bias-frontend




