# Use Node.js Alpine base image
FROM node:alpine

#Create and set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json /app/

#Install dependencies
RUN npm Install

# Copy the entire codebase to the working directory
COPY . /app/

# Expose the port your app runs on
EXPOSE 5137

# Define the command to start your application 

CMD ["npm", "run", "dev"]